# ──────────────────────────────────────────────────────────────────────────────
# Pages CMS config for a PaperMod‐based Hugo site in “profile” mode
# ──────────────────────────────────────────────────────────────────────────────

media:
  - name: images
    label: Images
    input: static/img
    output: /img
    extensions: [ jpg, jpeg, png, webp, svg ]

content:
  # Site configuration (PaperMod profile homepage)
  - name: siteConfig
    label: Site Configuration
    type: file
    path: config.yml
    format: yaml
    fields:
      - name: baseURL
        label: Site URL
        type: string
      - name: title
        label: Site Title
        type: string
      - name: languageCode
        label: Language
        type: string
      # PaperMod profile params
      - name: params.profile.name
        label: Your Name
        type: string
      - name: params.profile.image
        label: Avatar Image
        type: image
      - name: params.profile.bio
        label: Bio
        type: text
      - name: params.profile.location
        label: Location
        type: string
      - name: params.profile.website
        label: Website
        type: string
      - name: params.profile.showTags
        label: Show Tags?
        type: boolean
      # Social links
      - name: params.social.twitter
        label: Twitter Handle
        type: string
      - name: params.social.github
        label: GitHub Username
        type: string
      - name: params.social.linkedin
        label: LinkedIn URL
        type: string

  # About page (now using index.md under a folder)
  - name: about
    label: About
    type: file
    path: content/about/index.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  # Blog posts collection
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{slug}.md'
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: tags
        label: Tags
        type: text
        list: true
      - name: summary
        label: Summary
        type: text
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [ title, date, draft ]
      primary: title
      sort: [ date ]
      default:
        search: ''
        sort: date
        order: desc

components:
  image:
    label: Image
    type: image
    description: Select or upload an image from the Images media folder
