baseURL: "https://vakesz.com/"
title: "vakesz.com"
theme: "PaperMod"
languageCode: "en-us"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Personal blog of vakesz - Software Engineer sharing insights on backend development, C/Python programming, tech and personal adventures"
  author: "vakesz"
  keywords:
    - "personal blog"
    - "software engineer"
    - "backend developer"
    - "C programming"
    - "Python programming"
    - "tech blog"
    - "personal development"
    - "software engineering"
    - "backend development"
    - "C programming"
    - "Python"
    - "vakesz"
    - "self-taught developer"
    - "mountain biking"
    - "homelab"
    - "truenas"
    - "embedded systems"
    - "mentorship"
    - "career development"
    - "professional growth"
  
  # Theme Settings
  defaultTheme: "auto" # auto, light, dark
  disableThemeToggle: false
  
  # Display Settings
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowWordCount: false
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowToc: false
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: false
  
  # SEO Settings
  images: ["/img/cover-default.webp"]  # Default fallback image for social sharing
  cover:
    linkFullImages: true
    responsiveImages: true
    hidden: false
  
  # Enhanced SEO metadata
  schema:
    publisherType: "Person"
    sameAs:
      - "https://github.com/vakesz"
      - "https://twitter.com/vakeszqe"
      - "https://linkedin.com/in/gabor-pinkova"
      - "https://instagram.com/vakeszqe"
      - "https://youtube.com/@vakeszqe"
  
  # Default images for posts without covers
  defaultPostImage: "/img/cover-default.webp"
  
  # Search Settings
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
  
  # Profile Mode
  profileMode:
    enabled: true
    title: "vakesz"
    subtitle: "Software Engineer | Backend Developer | Tech Tinkerer"
    imageUrl: "img/me.webp"
    imageTitle: "vakesz"
    buttons:
      - name: "Posts"
        url: "/posts"
      - name: "About"
        url: "/about"
      - name: "Search"
        url: "/search"
  
  # Footer Settings
  footer:
    text: "© vakesz.com"
    hideCopyright: true
  
  # Assets (favicons, etc.)
  assets:
    disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    theme_color: "#2e2e33"
  
  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/vakesz"
    - name: "twitter"
      url: "https://twitter.com/vakeszqe"
    - name: "linkedin"
      url: "https://linkedin.com/in/gabor-pinkova"
    - name: "instagram"
      url: "https://instagram.com/vakeszqe"
    - name: "youtube"
      url: "https://youtube.com/@vakeszqe"
    - name: "rss"
      url: "/index.xml"
  
  # Share Buttons
  ShareButtons:
    - "linkedin"
    - "twitter"
    - "facebook"
    - "reddit"
  
  # Edit Post Settings
  editPost:
    URL: "https://github.com/vakesz/vakesz-hugo/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true
  
  # Comments
  comments: true
  commentProvider: "utterances"
  utterances:
    repo: "vakesz/vakesz-comments"
    issueterm: "pathname"
    label: "💬 comments"
    lightTheme: "github-light"
    darkTheme: "github-dark"

  # Analytics
  analytics:
    google:
      SiteVerificationTag: "wmIgcRkyiMpn8yLYNlSWr_CyKBP82dHZ0-edEILNaBY"

services:
  googleAnalytics:
    id: G-7FB5CVV3WZ
    consentMode: true

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 10
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 20
    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 30
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# Enable search functionality and sitemap
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
  section:
    - "HTML"
    - "RSS"

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
