baseURL = "https://vakesz.com/"
languageCode = "en-us"
title = "vakesz.com"
theme = "PaperMod"

[params]
  # Site Info
  description = "Personal blog of vakesz - Software Engineer sharing insights on backend development, C/Python programming, tech and personal adventures"
  author = "Gabor Pinkova"
  keywords = ["software engineering", "backend development", "C programming", "Python", "tech blog", "vakesz"]
  # Theme Settings
  defaultTheme = "auto" # auto, light, dark
  disableThemeToggle = false
  
  # Display Settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowWordCount = false
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc = false
  ShowFullTextinRSS = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = false
  
  # Search Settings
  fuseOpts.isCaseSensitive = false
  fuseOpts.shouldSort = true
  fuseOpts.location = 0
  fuseOpts.distance = 1000
  fuseOpts.threshold = 0.4
  fuseOpts.minMatchCharLength = 0
  fuseOpts.keys = ["title", "permalink", "summary", "content"]
  
  # Home Page Settings
  homeInfoParams.Title = "Welcome to My Blog"
  homeInfoParams.Content = "Description of your blog"
  
  # Profile Mode (uncomment to enable)
  profileMode.enabled = true
  profileMode.title = "vakesz"
  profileMode.subtitle = "Software Engineer | Backend Developer | Tech Tinkerer"
  profileMode.imageUrl = "img/avatar.webp"
  profileMode.imageWidth = 120
  profileMode.imageHeight = 120
  profileMode.imageTitle = "Gabor Pinkova"
  profileMode.buttons = [
    {name = "Posts", url = "/posts"},
    {name = "About", url = "/about"},
    {name = "Search", url = "/search"}
  ]
  
  # Footer Settings
  footer.text = "© 2025 - vakesz.com"
  footer.hideCopyright = true
  
  # Assets (favicons, etc.)
  assets.favicon = "favicon.ico"
  assets.favicon16x16 = "favicon-16x16.png"
  assets.favicon32x32 = "favicon-32x32.png"
  assets.apple_touch_icon = "apple-touch-icon.png"
  assets.safari_pinned_tab = "safari-pinned-tab.svg"
  assets.theme_color = "#2e2e33"
  # assets.msapplication_TileColor = "#2e2e33"
  
  # Social Icons - Add your social media links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/vakesz"
  
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/vakeszqe"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/gabor-pinkova"
  
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/vakeszqe"
  
  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@vakeszable"
  
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"
  
  # Share Buttons (customize which ones to show)
  ShareButtons = ["linkedin", "twitter", "facebook", "reddit"]
  
  # Edit Post Settings
  editPost.URL = "https://github.com/vakesz/vakesz-hugo/tree/main/content"
  editPost.Text = "Suggest Changes"
  editPost.appendFilePath = true
  
  # Analytics
  # analytics.google.SiteVerificationTag = "your-google-site-verification"
  # Enable Google Analytics 4
  # googleAnalytics = "G-XXXXXXXXXX"
  # analytics.bing.SiteVerificationTag = "your-bing-verification"
  # analytics.yandex.SiteVerificationTag = "your-yandex-verification"
  # analytics.naver.SiteVerificationTag = "your-naver-verification"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 10

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 20

    [[menu.main]]
    identifier = "search"
    name       = "Search"
    url        = "/search/"
    weight     = 30

    [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 40

# Enable search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]
